# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f44f88ec397cfb6398f7fe28081af2608ead0271f3379a974abae3bde0a9ebf492c4ee6294aa0f02772e658c81fdc8dfaed17d6b7791c146fb61b1531c7d066

test:
  secret_key_base: 71a52d353e78ae015c6e0068f8c53462b9408b009fe41a81ed9cccbd1b8c22ba1760cd01231a08298fa840c42f56d0eeb01feca7c240dfd5fbadeaef0c17edb3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
